/**
 * Represents a contact object.
 */
export interface ContactInterface {
  /** The unique identifier of the contact, generated by Firebase (optional). */
  id?: string;
  /** The email address of the contact. */
  email: string;
  /** The full name of the contact. */
  name: string;
  /** The phone number of the contact. */
  phone: number;
  /** The color associated with the contact for visual representation. */
  color: string;
}