/**
 * Represents a subtask within a larger task.
 */
export interface Subtask {
  /** The title of the subtask. */
  title: string;
  /** Indicates if the subtask has been completed. */
  completed: boolean;
  /** Indicates if the subtask is currently being edited. */
  isEditing?: boolean;
}

/**
 * Represents a task object.
 */
export interface TaskInterface {
  /** The unique identifier of the task, generated by Firebase (optional). */
  id?: string;
  /** An array of user IDs that the task is assigned to (optional). */
  assignedTo?: string[];
  /** The category of the task (cannot be null). */
  category: string | null;
  /** The date when the task was created (optional). */
  created?: Date;
  /** The due date of the task (cannot be null). */
  date: string;
  /** A detailed description of the task (optional). */
  description?: string;
  /** The date when the task was last edited (optional). */
  edited?: Date;
  /** The priority level of the task (optional). */
  priority?: 'urgent' | 'medium' | 'low';
  /** An array of subtasks associated with the main task (optional). */
  subtask?: Subtask[]; // Or an array of Subtask objects with a completed status
  /** The title of the task (cannot be null). */
  title: string;
  /** The current status of the task. */
  status: 'Todo' | 'In Progress' | 'Await Feedback' | 'Done';
}